language: node_js
dist: trusty
sudo: true
node_js:
  - "node"
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis
  - EVM_EMACS=remacs-git-snapshot-travis
before_install:
  - export PATH="/home/travis/.cask/bin:/home/travis/.evm/bin:$PATH"
install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - npm install
script:
  - ./test-travis.sh
